"""Seed gadget data for GadgetsHub."""

GADGETS_SEED = [
    # ==================== SMARTPHONES (10) ====================
    {
        "name": "iPhone 15 Pro Max",
        "brand": "Apple",
        "category": "smartphones",
        "price": 159900,
        "rating": 4.8,
        "image": "https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800&q=80",
        "description": "The most powerful iPhone ever, crafted in titanium with the A17 Pro chip.",
        "specs": {
            "Display": "6.7 inch Super Retina XDR OLED",
            "Processor": "A17 Pro Bionic",
            "RAM": "8 GB",
            "Storage": "256 GB",
            "Battery": "4422 mAh",
            "Camera": "48MP Triple + LiDAR",
            "OS": "iOS 17",
            "Weight": "221 g",
        },
    },
    {
        "name": "Samsung Galaxy S24 Ultra",
        "brand": "Samsung",
        "category": "smartphones",
        "price": 129999,
        "rating": 4.7,
        "image": "https://images.unsplash.com/photo-1610945264803-c22b62d2a7b3?w=800&q=80",
        "description": "AI-powered flagship with built-in S Pen and 200MP camera.",
        "specs": {
            "Display": "6.8 inch Dynamic AMOLED 2X",
            "Processor": "Snapdragon 8 Gen 3",
            "RAM": "12 GB",
            "Storage": "256 GB",
            "Battery": "5000 mAh",
            "Camera": "200MP Quad",
            "OS": "Android 14 (One UI 6.1)",
            "Weight": "233 g",
        },
    },
    {
        "name": "Google Pixel 8 Pro",
        "brand": "Google",
        "category": "smartphones",
        "price": 106999,
        "rating": 4.6,
        "image": "https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=800&q=80",
        "description": "AI-first smartphone with best-in-class computational photography.",
        "specs": {
            "Display": "6.7 inch LTPO OLED",
            "Processor": "Google Tensor G3",
            "RAM": "12 GB",
            "Storage": "128 GB",
            "Battery": "5050 mAh",
            "Camera": "50MP Triple",
            "OS": "Android 14",
            "Weight": "213 g",
        },
    },
    {
        "name": "OnePlus 12",
        "brand": "OnePlus",
        "category": "smartphones",
        "price": 64999,
        "rating": 4.5,
        "image": "https://images.unsplash.com/photo-1512054502232-10a0a035d672?w=800&q=80",
        "description": "Flagship killer with Hasselblad optics and 100W fast charging.",
        "specs": {
            "Display": "6.82 inch LTPO AMOLED",
            "Processor": "Snapdragon 8 Gen 3",
            "RAM": "12 GB",
            "Storage": "256 GB",
            "Battery": "5400 mAh",
            "Camera": "50MP Triple (Hasselblad)",
            "OS": "Android 14 (OxygenOS 14)",
            "Weight": "220 g",
        },
    },
    {
        "name": "Xiaomi 14 Ultra",
        "brand": "Xiaomi",
        "category": "smartphones",
        "price": 99999,
        "rating": 4.6,
        "image": "https://images.unsplash.com/photo-1567581935884-3349723552ca?w=800&q=80",
        "description": "Photography powerhouse co-engineered with Leica.",
        "specs": {
            "Display": "6.73 inch LTPO AMOLED",
            "Processor": "Snapdragon 8 Gen 3",
            "RAM": "16 GB",
            "Storage": "512 GB",
            "Battery": "5300 mAh",
            "Camera": "50MP Quad (Leica)",
            "OS": "Android 14 (HyperOS)",
            "Weight": "229 g",
        },
    },
    {
        "name": "iPhone 15",
        "brand": "Apple",
        "category": "smartphones",
        "price": 79900,
        "rating": 4.6,
        "image": "https://images.unsplash.com/photo-1592286927505-1def25115558?w=800&q=80",
        "description": "The everyday iPhone with Dynamic Island and USB-C.",
        "specs": {
            "Display": "6.1 inch Super Retina XDR OLED",
            "Processor": "A16 Bionic",
            "RAM": "6 GB",
            "Storage": "128 GB",
            "Battery": "3349 mAh",
            "Camera": "48MP Dual",
            "OS": "iOS 17",
            "Weight": "171 g",
        },
    },
    {
        "name": "Samsung Galaxy S24",
        "brand": "Samsung",
        "category": "smartphones",
        "price": 74999,
        "rating": 4.5,
        "image": "https://images.unsplash.com/photo-1616348436168-de43ad0db179?w=800&q=80",
        "description": "Compact flagship with Galaxy AI and stunning display.",
        "specs": {
            "Display": "6.2 inch Dynamic AMOLED 2X",
            "Processor": "Exynos 2400",
            "RAM": "8 GB",
            "Storage": "128 GB",
            "Battery": "4000 mAh",
            "Camera": "50MP Triple",
            "OS": "Android 14 (One UI 6.1)",
            "Weight": "167 g",
        },
    },
    {
        "name": "Nothing Phone (2)",
        "brand": "Nothing",
        "category": "smartphones",
        "price": 44999,
        "rating": 4.3,
        "image": "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&q=80",
        "description": "Transparent design with iconic Glyph Interface LEDs.",
        "specs": {
            "Display": "6.7 inch LTPO OLED",
            "Processor": "Snapdragon 8+ Gen 1",
            "RAM": "12 GB",
            "Storage": "256 GB",
            "Battery": "4700 mAh",
            "Camera": "50MP Dual",
            "OS": "Android 13 (Nothing OS 2.0)",
            "Weight": "201 g",
        },
    },
    {
        "name": "OPPO Find X7 Ultra",
        "brand": "OPPO",
        "category": "smartphones",
        "price": 89999,
        "rating": 4.4,
        "image": "https://images.unsplash.com/photo-1580910051074-3eb694886505?w=800&q=80",
        "description": "Dual periscope cameras with Hasselblad partnership.",
        "specs": {
            "Display": "6.82 inch LTPO AMOLED",
            "Processor": "Snapdragon 8 Gen 3",
            "RAM": "16 GB",
            "Storage": "512 GB",
            "Battery": "5000 mAh",
            "Camera": "50MP Quad (Hasselblad)",
            "OS": "Android 14 (ColorOS 14)",
            "Weight": "221 g",
        },
    },
    {
        "name": "iPhone 14",
        "brand": "Apple",
        "category": "smartphones",
        "price": 59900,
        "rating": 4.5,
        "image": "https://images.unsplash.com/photo-1663499482523-1c0c1bae4ce1?w=800&q=80",
        "description": "Reliable performance with great cameras and battery life.",
        "specs": {
            "Display": "6.1 inch Super Retina XDR OLED",
            "Processor": "A15 Bionic",
            "RAM": "6 GB",
            "Storage": "128 GB",
            "Battery": "3279 mAh",
            "Camera": "12MP Dual",
            "OS": "iOS 16",
            "Weight": "172 g",
        },
    },
    # ==================== LAPTOPS (8) ====================
    {
        "name": "MacBook Pro 16 M3 Max",
        "brand": "Apple",
        "category": "laptops",
        "price": 349900,
        "rating": 4.9,
        "image": "https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=800&q=80",
        "description": "Powerhouse for pros with M3 Max chip and Liquid Retina XDR display.",
        "specs": {
            "Display": "16.2 inch Liquid Retina XDR",
            "Processor": "Apple M3 Max (16-core CPU)",
            "RAM": "36 GB",
            "Storage": "1 TB SSD",
            "Battery": "100 Wh (22 hr)",
            "Graphics": "40-core GPU",
            "OS": "macOS Sonoma",
            "Weight": "2.16 kg",
        },
    },
    {
        "name": "Dell XPS 15",
        "brand": "Dell",
        "category": "laptops",
        "price": 189990,
        "rating": 4.6,
        "image": "https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=800&q=80",
        "description": "Premium creator laptop with OLED display and Intel i9.",
        "specs": {
            "Display": "15.6 inch 3.5K OLED",
            "Processor": "Intel Core i9-13900H",
            "RAM": "32 GB DDR5",
            "Storage": "1 TB SSD",
            "Battery": "86 Wh (13 hr)",
            "Graphics": "NVIDIA RTX 4070 8GB",
            "OS": "Windows 11",
            "Weight": "1.92 kg",
        },
    },
    {
        "name": "ASUS ROG Zephyrus G14",
        "brand": "ASUS",
        "category": "laptops",
        "price": 154990,
        "rating": 4.7,
        "image": "https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=800&q=80",
        "description": "Compact powerhouse for gamers and creators with AniMe Matrix display.",
        "specs": {
            "Display": "14 inch QHD+ OLED 120Hz",
            "Processor": "AMD Ryzen 9 7940HS",
            "RAM": "32 GB",
            "Storage": "1 TB SSD",
            "Battery": "76 Wh (10 hr)",
            "Graphics": "NVIDIA RTX 4070 8GB",
            "OS": "Windows 11",
            "Weight": "1.72 kg",
        },
    },
    {
        "name": "Lenovo ThinkPad X1 Carbon Gen 12",
        "brand": "Lenovo",
        "category": "laptops",
        "price": 174990,
        "rating": 4.5,
        "image": "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=800&q=80",
        "description": "Lightweight business ultrabook with military-grade durability.",
        "specs": {
            "Display": "14 inch 2.8K OLED",
            "Processor": "Intel Core Ultra 7 155H",
            "RAM": "32 GB LPDDR5x",
            "Storage": "1 TB SSD",
            "Battery": "57 Wh (15 hr)",
            "Graphics": "Intel Arc iGPU",
            "OS": "Windows 11 Pro",
            "Weight": "1.09 kg",
        },
    },
    {
        "name": "MacBook Air 15 M3",
        "brand": "Apple",
        "category": "laptops",
        "price": 134900,
        "rating": 4.7,
        "image": "https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?w=800&q=80",
        "description": "Thin, light and silent with Apple's M3 efficiency.",
        "specs": {
            "Display": "15.3 inch Liquid Retina",
            "Processor": "Apple M3 (8-core CPU)",
            "RAM": "16 GB",
            "Storage": "512 GB SSD",
            "Battery": "66.5 Wh (18 hr)",
            "Graphics": "10-core GPU",
            "OS": "macOS Sonoma",
            "Weight": "1.51 kg",
        },
    },
    {
        "name": "HP Spectre x360 14",
        "brand": "HP",
        "category": "laptops",
        "price": 139990,
        "rating": 4.4,
        "image": "https://images.unsplash.com/photo-1587614382346-4ec70e388b28?w=800&q=80",
        "description": "Convertible 2-in-1 with premium design and OLED touchscreen.",
        "specs": {
            "Display": "14 inch 2.8K OLED Touch",
            "Processor": "Intel Core Ultra 7 155H",
            "RAM": "16 GB LPDDR5x",
            "Storage": "1 TB SSD",
            "Battery": "68 Wh (12 hr)",
            "Graphics": "Intel Arc iGPU",
            "OS": "Windows 11",
            "Weight": "1.44 kg",
        },
    },
    {
        "name": "Razer Blade 16",
        "brand": "Razer",
        "category": "laptops",
        "price": 329990,
        "rating": 4.6,
        "image": "https://images.unsplash.com/photo-1629429407759-01cd3d7cfb38?w=800&q=80",
        "description": "Top-tier gaming laptop with dual-mode Mini LED display.",
        "specs": {
            "Display": "16 inch UHD+/FHD+ Dual-Mode Mini LED",
            "Processor": "Intel Core i9-14900HX",
            "RAM": "32 GB DDR5",
            "Storage": "2 TB SSD",
            "Battery": "95.2 Wh (6 hr)",
            "Graphics": "NVIDIA RTX 4090 16GB",
            "OS": "Windows 11",
            "Weight": "2.45 kg",
        },
    },
    {
        "name": "Microsoft Surface Laptop 6",
        "brand": "Microsoft",
        "category": "laptops",
        "price": 149990,
        "rating": 4.3,
        "image": "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=800&q=80",
        "description": "AI PC with Copilot+ features and premium alcantara keyboard.",
        "specs": {
            "Display": "13.5 inch PixelSense Touch",
            "Processor": "Intel Core Ultra 7 165H",
            "RAM": "16 GB LPDDR5x",
            "Storage": "512 GB SSD",
            "Battery": "47 Wh (19 hr)",
            "Graphics": "Intel Arc iGPU",
            "OS": "Windows 11",
            "Weight": "1.38 kg",
        },
    },
    # ==================== HEADPHONES (8) ====================
    {
        "name": "Sony WH-1000XM5",
        "brand": "Sony",
        "category": "headphones",
        "price": 29990,
        "rating": 4.8,
        "image": "https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=800&q=80",
        "description": "Industry-leading noise cancellation with exceptional audio quality.",
        "specs": {
            "Type": "Over-ear Wireless",
            "Driver": "30mm Dynamic",
            "Battery": "30 hours",
            "ANC": "Yes (Adaptive)",
            "Connectivity": "Bluetooth 5.2, 3.5mm",
            "Weight": "250 g",
            "Codec": "LDAC, AAC, SBC",
            "Charging": "USB-C (Fast)",
        },
    },
    {
        "name": "Apple AirPods Max",
        "brand": "Apple",
        "category": "headphones",
        "price": 59900,
        "rating": 4.6,
        "image": "https://images.unsplash.com/photo-1583394838336-acd977736f90?w=800&q=80",
        "description": "Premium over-ear with H1 chip and spatial audio.",
        "specs": {
            "Type": "Over-ear Wireless",
            "Driver": "40mm Custom",
            "Battery": "20 hours",
            "ANC": "Yes (Adaptive)",
            "Connectivity": "Bluetooth 5.0, Lightning",
            "Weight": "384 g",
            "Codec": "AAC",
            "Charging": "Lightning",
        },
    },
    {
        "name": "Bose QuietComfort Ultra",
        "brand": "Bose",
        "category": "headphones",
        "price": 34900,
        "rating": 4.7,
        "image": "https://images.unsplash.com/photo-1545127398-14699f92334b?w=800&q=80",
        "description": "Legendary Bose comfort with immersive audio technology.",
        "specs": {
            "Type": "Over-ear Wireless",
            "Driver": "35mm Dynamic",
            "Battery": "24 hours",
            "ANC": "Yes",
            "Connectivity": "Bluetooth 5.3, 3.5mm",
            "Weight": "253 g",
            "Codec": "aptX Adaptive, AAC, SBC",
            "Charging": "USB-C",
        },
    },
    {
        "name": "Sennheiser Momentum 4",
        "brand": "Sennheiser",
        "category": "headphones",
        "price": 34990,
        "rating": 4.6,
        "image": "https://images.unsplash.com/photo-1599669454699-248893623440?w=800&q=80",
        "description": "Audiophile-grade sound with 60-hour battery life.",
        "specs": {
            "Type": "Over-ear Wireless",
            "Driver": "42mm Dynamic",
            "Battery": "60 hours",
            "ANC": "Yes (Adaptive)",
            "Connectivity": "Bluetooth 5.2, 3.5mm",
            "Weight": "293 g",
            "Codec": "aptX Adaptive, AAC, SBC",
            "Charging": "USB-C",
        },
    },
    {
        "name": "Sony WF-1000XM5",
        "brand": "Sony",
        "category": "headphones",
        "price": 24990,
        "rating": 4.7,
        "image": "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&q=80",
        "description": "True wireless earbuds with class-leading noise cancellation.",
        "specs": {
            "Type": "In-ear True Wireless",
            "Driver": "8.4mm Dynamic X",
            "Battery": "8 hrs (24 hrs w/ case)",
            "ANC": "Yes",
            "Connectivity": "Bluetooth 5.3",
            "Weight": "5.9 g each",
            "Codec": "LDAC, AAC, SBC",
            "Charging": "USB-C, Wireless",
        },
    },
    {
        "name": "Apple AirPods Pro 2",
        "brand": "Apple",
        "category": "headphones",
        "price": 24900,
        "rating": 4.7,
        "image": "https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=800&q=80",
        "description": "USB-C variant with adaptive audio and conversation awareness.",
        "specs": {
            "Type": "In-ear True Wireless",
            "Driver": "Custom high-excursion",
            "Battery": "6 hrs (30 hrs w/ case)",
            "ANC": "Yes (Adaptive)",
            "Connectivity": "Bluetooth 5.3",
            "Weight": "5.3 g each",
            "Codec": "AAC",
            "Charging": "USB-C, MagSafe, Qi",
        },
    },
    {
        "name": "Bose QuietComfort Earbuds II",
        "brand": "Bose",
        "category": "headphones",
        "price": 26900,
        "rating": 4.5,
        "image": "https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?w=800&q=80",
        "description": "World-class noise cancellation in a compact earbud.",
        "specs": {
            "Type": "In-ear True Wireless",
            "Driver": "9.3mm Dynamic",
            "Battery": "6 hrs (24 hrs w/ case)",
            "ANC": "Yes",
            "Connectivity": "Bluetooth 5.3",
            "Weight": "6.24 g each",
            "Codec": "AAC, SBC",
            "Charging": "USB-C",
        },
    },
    {
        "name": "Samsung Galaxy Buds 2 Pro",
        "brand": "Samsung",
        "category": "headphones",
        "price": 17999,
        "rating": 4.4,
        "image": "https://images.unsplash.com/photo-1631867675167-90a456a90863?w=800&q=80",
        "description": "Hi-Fi 24-bit audio with intelligent ANC.",
        "specs": {
            "Type": "In-ear True Wireless",
            "Driver": "10mm + 5.3mm Coaxial",
            "Battery": "5 hrs (18 hrs w/ case)",
            "ANC": "Yes",
            "Connectivity": "Bluetooth 5.3",
            "Weight": "5.5 g each",
            "Codec": "Samsung Seamless, AAC, SBC",
            "Charging": "USB-C, Wireless",
        },
    },
    # ==================== SMARTWATCHES (7) ====================
    {
        "name": "Apple Watch Ultra 2",
        "brand": "Apple",
        "category": "smartwatches",
        "price": 89900,
        "rating": 4.7,
        "image": "https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=800&q=80",
        "description": "Rugged titanium design for extreme adventures.",
        "specs": {
            "Display": "49mm Always-On Retina",
            "Processor": "Apple S9 SiP",
            "Battery": "36 hrs (72 hrs low-power)",
            "GPS": "Dual-frequency L1/L5",
            "Water Resistance": "100m WR10",
            "Sensors": "ECG, SpO2, Depth, Temp",
            "OS": "watchOS 10",
            "Weight": "61.4 g",
        },
    },
    {
        "name": "Samsung Galaxy Watch 6 Classic",
        "brand": "Samsung",
        "category": "smartwatches",
        "price": 41999,
        "rating": 4.5,
        "image": "https://images.unsplash.com/photo-1617043786394-f977fa12eddf?w=800&q=80",
        "description": "Iconic rotating bezel with advanced health sensors.",
        "specs": {
            "Display": "47mm Super AMOLED",
            "Processor": "Exynos W930 Dual-Core",
            "Battery": "40 hrs",
            "GPS": "L1",
            "Water Resistance": "5 ATM + IP68",
            "Sensors": "ECG, BP, SpO2, BIA",
            "OS": "Wear OS 4 (One UI Watch 5)",
            "Weight": "59 g",
        },
    },
    {
        "name": "Apple Watch Series 9",
        "brand": "Apple",
        "category": "smartwatches",
        "price": 41900,
        "rating": 4.7,
        "image": "https://images.unsplash.com/photo-1551816230-ef5deaed4a26?w=800&q=80",
        "description": "Brighter display and Double Tap gesture with S9 chip.",
        "specs": {
            "Display": "45mm Always-On Retina",
            "Processor": "Apple S9 SiP",
            "Battery": "18 hrs (36 hrs low-power)",
            "GPS": "L1",
            "Water Resistance": "50m WR50",
            "Sensors": "ECG, SpO2, Temp",
            "OS": "watchOS 10",
            "Weight": "38.7 g",
        },
    },
    {
        "name": "Garmin Fenix 7X Pro",
        "brand": "Garmin",
        "category": "smartwatches",
        "price": 89990,
        "rating": 4.8,
        "image": "https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=800&q=80",
        "description": "Multisport GPS watch with solar charging and weeks of battery.",
        "specs": {
            "Display": "51mm Solar MIP Touch",
            "Processor": "Garmin proprietary",
            "Battery": "28 days (37 w/ solar)",
            "GPS": "Multi-band",
            "Water Resistance": "10 ATM",
            "Sensors": "Pulse Ox, HR, Temp",
            "OS": "Garmin OS",
            "Weight": "89 g",
        },
    },
    {
        "name": "Google Pixel Watch 2",
        "brand": "Google",
        "category": "smartwatches",
        "price": 39900,
        "rating": 4.3,
        "image": "https://images.unsplash.com/photo-1617625802921-38e4e2893c0a?w=800&q=80",
        "description": "Fitbit-powered health tracking with classy circular design.",
        "specs": {
            "Display": "41mm Always-On AMOLED",
            "Processor": "Snapdragon W5+ Gen 1",
            "Battery": "24 hrs",
            "GPS": "L1",
            "Water Resistance": "5 ATM",
            "Sensors": "ECG, SpO2, Skin Temp, cEDA",
            "OS": "Wear OS 4",
            "Weight": "31 g",
        },
    },
    {
        "name": "OnePlus Watch 2",
        "brand": "OnePlus",
        "category": "smartwatches",
        "price": 24999,
        "rating": 4.3,
        "image": "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=800&q=80",
        "description": "100-hour battery life in Wear OS smart mode.",
        "specs": {
            "Display": "46mm AMOLED 466x466",
            "Processor": "Snapdragon W5 + BES 2700",
            "Battery": "100 hrs Smart Mode",
            "GPS": "Dual-frequency",
            "Water Resistance": "5 ATM + IP68",
            "Sensors": "HR, SpO2, Skin Temp",
            "OS": "Wear OS 4",
            "Weight": "49 g",
        },
    },
    {
        "name": "Fitbit Charge 6",
        "brand": "Fitbit",
        "category": "smartwatches",
        "price": 15999,
        "rating": 4.2,
        "image": "https://images.unsplash.com/photo-1575311373937-040b8e1fd1ae?w=800&q=80",
        "description": "Advanced fitness tracker with Google apps integration.",
        "specs": {
            "Display": "AMOLED Color Touchscreen",
            "Processor": "Fitbit proprietary",
            "Battery": "7 days",
            "GPS": "Built-in",
            "Water Resistance": "5 ATM",
            "Sensors": "ECG, SpO2, EDA, HR",
            "OS": "Fitbit OS",
            "Weight": "37.64 g",
        },
    },
    # ==================== TABLETS (7) ====================
    {
        "name": "iPad Pro 13 M4",
        "brand": "Apple",
        "category": "tablets",
        "price": 129900,
        "rating": 4.8,
        "image": "https://images.unsplash.com/photo-1585789575054-13cf7b3fde90?w=800&q=80",
        "description": "Thinnest Apple product ever with tandem OLED and M4 chip.",
        "specs": {
            "Display": "13 inch Ultra Retina XDR OLED",
            "Processor": "Apple M4 (10-core)",
            "RAM": "8 GB",
            "Storage": "256 GB",
            "Battery": "38.99 Wh (10 hr)",
            "Camera": "12MP rear + 12MP front",
            "OS": "iPadOS 17",
            "Weight": "579 g",
        },
    },
    {
        "name": "Samsung Galaxy Tab S9 Ultra",
        "brand": "Samsung",
        "category": "tablets",
        "price": 108999,
        "rating": 4.6,
        "image": "https://images.unsplash.com/photo-1561154464-82e9adf32764?w=800&q=80",
        "description": "Massive 14.6 inch AMOLED display with S Pen included.",
        "specs": {
            "Display": "14.6 inch Dynamic AMOLED 2X",
            "Processor": "Snapdragon 8 Gen 2 for Galaxy",
            "RAM": "12 GB",
            "Storage": "256 GB",
            "Battery": "11200 mAh",
            "Camera": "13MP Dual + 12MP Dual front",
            "OS": "Android 13 (One UI 5.1)",
            "Weight": "732 g",
        },
    },
    {
        "name": "iPad Air 13 M2",
        "brand": "Apple",
        "category": "tablets",
        "price": 84900,
        "rating": 4.7,
        "image": "https://images.unsplash.com/photo-1623126908029-58cb08a2b272?w=800&q=80",
        "description": "All-screen design with M2 performance for creators on the go.",
        "specs": {
            "Display": "13 inch Liquid Retina",
            "Processor": "Apple M2 (8-core)",
            "RAM": "8 GB",
            "Storage": "128 GB",
            "Battery": "36.59 Wh (10 hr)",
            "Camera": "12MP rear + 12MP front",
            "OS": "iPadOS 17",
            "Weight": "617 g",
        },
    },
    {
        "name": "Microsoft Surface Pro 10",
        "brand": "Microsoft",
        "category": "tablets",
        "price": 108990,
        "rating": 4.4,
        "image": "https://images.unsplash.com/photo-1625961332771-3f40b0e2bdcf?w=800&q=80",
        "description": "2-in-1 AI PC with Intel Core Ultra and OLED display option.",
        "specs": {
            "Display": "13 inch PixelSense Flow Touch",
            "Processor": "Intel Core Ultra 7 165U",
            "RAM": "16 GB LPDDR5x",
            "Storage": "512 GB SSD",
            "Battery": "48 Wh (19 hr)",
            "Camera": "10.5MP rear + 1440p front",
            "OS": "Windows 11 Pro",
            "Weight": "895 g",
        },
    },
    {
        "name": "iPad 10th Gen",
        "brand": "Apple",
        "category": "tablets",
        "price": 36900,
        "rating": 4.5,
        "image": "https://images.unsplash.com/photo-1619117538086-12ac2e0b1b99?w=800&q=80",
        "description": "Colorful redesigned iPad with USB-C and landscape camera.",
        "specs": {
            "Display": "10.9 inch Liquid Retina",
            "Processor": "Apple A14 Bionic",
            "RAM": "4 GB",
            "Storage": "64 GB",
            "Battery": "28.6 Wh (10 hr)",
            "Camera": "12MP rear + 12MP front",
            "OS": "iPadOS 17",
            "Weight": "477 g",
        },
    },
    {
        "name": "OnePlus Pad",
        "brand": "OnePlus",
        "category": "tablets",
        "price": 37999,
        "rating": 4.3,
        "image": "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800&q=80",
        "description": "Premium aluminum build with 144Hz display and flagship performance.",
        "specs": {
            "Display": "11.61 inch 2.8K 144Hz",
            "Processor": "MediaTek Dimensity 9000",
            "RAM": "8 GB",
            "Storage": "128 GB",
            "Battery": "9510 mAh",
            "Camera": "13MP rear + 8MP front",
            "OS": "Android 13 (OxygenOS 13.1)",
            "Weight": "552 g",
        },
    },
    {
        "name": "Xiaomi Pad 6 Pro",
        "brand": "Xiaomi",
        "category": "tablets",
        "price": 39999,
        "rating": 4.2,
        "image": "https://images.unsplash.com/photo-1593640408182-31c70c8268f5?w=800&q=80",
        "description": "Performance flagship tablet with 144Hz display at a great price.",
        "specs": {
            "Display": "11 inch 2.8K 144Hz",
            "Processor": "Snapdragon 8+ Gen 1",
            "RAM": "8 GB",
            "Storage": "256 GB",
            "Battery": "8600 mAh",
            "Camera": "50MP rear + 20MP front",
            "OS": "Android 13 (MIUI 14)",
            "Weight": "490 g",
        },
    },
]
